# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Joeyonng's Notebook
author: Litao Qiao @Joeyonng
logo: logo.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: 'off'

# Allow display math ($$) within an inline context (doesn't work at 0.12.1)
parse:
  myst_dmath_double_inline: true
  
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    
# Remove binder button on the top right corner
launch_buttons:
  binderhub_url: ""

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js